Vagrant.configure("2") do |config|
    config.vm.define "dev" do |dev|
      dev.vm.box = "gusztavvargadr/ubuntu-server-2204-lts"

      dev.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
	    vb.customize ["modifyvm", :id, "--audio", "none"]
        vb.name = "kafka-cluster-broker-2"
      end

      config.vm.provision "shell", privileged: false, inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install mc -y

        VER="4.1.1"
        wget "https://dlcdn.apache.org/kafka/${VER}/kafka_2.13-${VER}.tgz"

        sudo mkdir -p "/opt/kafka_2.13-${VER}"
        sudo tar -xzf "kafka_2.13-${VER}.tgz" -C "/opt/kafka_2.13-${VER}" --strip-components=1
        sudo ln -sfn "/opt/kafka_2.13-${VER}" /opt/kafka
        sudo mkdir -p /opt/kafka/config-orig
        sudo cp -a /opt/kafka/config/. /opt/kafka/config-orig/
......SHELL
    end
end
