Vagrant.configure("2") do |config|
    config.vm.define "dev" do |dev|
      dev.vm.box = "gusztavvargadr/ubuntu-server-2204-lts"    

      dev.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
	    vb.customize ["modifyvm", :id, "--audio", "none"]
        vb.name = "kafka-cluster-broker-3" 
      end
      
      config.vm.provision "shell", privileged: false, inline: <<-SHELL
        sudo apt-get install mc -y                
      SHELL
    end
end
